---
name: Build Fedora Kernel

# yamllint disable-line rule:truthy
on: [push]

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
# https://hub.docker.com/_/alpine
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "YamlLint"
        run: |
          docker run \
            --rm \
            -w /repo \
            -v $(pwd):/repo \
            -t \
            alpine:3.20 /bin/sh -c " \
              apk add --no-cache py-pip python3 bash \
              && pip3 install --break-system-packages yamllint \
              && yamllint -s . \
            "
      - name: "ShellCheck"
        run: |
          docker run \
            --rm \
            -w /repo \
            -v $(pwd):/repo \
            -t \
            alpine:3.20 /bin/sh -c " \
              apk add --no-cache shellcheck bash \
              && shellcheck $(find . -type f -name "*.sh" |  tr '\n' ' ')
            "
      - name: "AgentInfo"
        run: ./.github/agent-info.sh

  build:
    runs-on: ubuntu-24.04
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "AgentInfo"
        run: ./.github/agent-info.sh
      - name: "Runner storage cleanup"
        run: ./.github/cleanup-runner.sh
      - name: "AgentInfo"
        run: ./.github/agent-info.sh
      - name: "Build Fedora Kernel"
        timeout-minutes: 1200
        run: ./build_in_docker.sh
        env:
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            ./output_zip/*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: true
          files: |
            ./output_zip/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # You don't need to add this in secrets it's by default.
      - name: "AgentInfo"
        run: ./.github/agent-info.sh
