---
name: Update yum repo on GitHub Pages

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "Update yum repo on GitHub Pages..."
        run: ./publish.sh
