---
name: Update yum repo on heroku

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Update yum repo on heroku..."
        run: ./publish.sh
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}
