---
name: Update yum repo on heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Update yum repo on heroku..."
        run: ./publish.sh
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
